# coding: utf-8

# flake8: noqa
"""
    SparkleHub API

    Test description  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: alex@shishenko.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from sparklehub.openapi_client.models.channel import Channel
from sparklehub.openapi_client.models.package import Package
from sparklehub.openapi_client.models.release import Release
from sparklehub.openapi_client.models.release_note import ReleaseNote
