# coding: utf-8

"""
    SparkleHub API

    Test description  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: alex@shishenko.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sparklehub.openapi_client.configuration import Configuration


class ReleaseNote(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'release': 'str',
        'text': 'str',
        'language': 'str'
    }

    attribute_map = {
        'id': 'id',
        'release': 'release',
        'text': 'text',
        'language': 'language'
    }

    def __init__(self, id=None, release=None, text=None, language=None, local_vars_configuration=None):  # noqa: E501
        """ReleaseNote - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._release = None
        self._text = None
        self._language = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.release = release
        self.text = text
        if language is not None:
            self.language = language

    @property
    def id(self):
        """Gets the id of this ReleaseNote.  # noqa: E501


        :return: The id of this ReleaseNote.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ReleaseNote.


        :param id: The id of this ReleaseNote.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def release(self):
        """Gets the release of this ReleaseNote.  # noqa: E501


        :return: The release of this ReleaseNote.  # noqa: E501
        :rtype: str
        """
        return self._release

    @release.setter
    def release(self, release):
        """Sets the release of this ReleaseNote.


        :param release: The release of this ReleaseNote.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and release is None:  # noqa: E501
            raise ValueError("Invalid value for `release`, must not be `None`")  # noqa: E501

        self._release = release

    @property
    def text(self):
        """Gets the text of this ReleaseNote.  # noqa: E501


        :return: The text of this ReleaseNote.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this ReleaseNote.


        :param text: The text of this ReleaseNote.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and text is None:  # noqa: E501
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                text is not None and len(text) < 1):
            raise ValueError("Invalid value for `text`, length must be greater than or equal to `1`")  # noqa: E501

        self._text = text

    @property
    def language(self):
        """Gets the language of this ReleaseNote.  # noqa: E501


        :return: The language of this ReleaseNote.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this ReleaseNote.


        :param language: The language of this ReleaseNote.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                language is not None and len(language) > 2):
            raise ValueError("Invalid value for `language`, length must be less than or equal to `2`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                language is not None and len(language) < 1):
            raise ValueError("Invalid value for `language`, length must be greater than or equal to `1`")  # noqa: E501

        self._language = language

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReleaseNote):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReleaseNote):
            return True

        return self.to_dict() != other.to_dict()
