# coding: utf-8

"""
    SparkleHub API

    Test description  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: alex@shishenko.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sparklehub.openapi_client
from sparklehub.openapi_client.models.package import Package  # noqa: E501
from sparklehub.openapi_client.rest import ApiException

class TestPackage(unittest.TestCase):
    """Package unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Package
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sparklehub.openapi_client.models.package.Package()  # noqa: E501
        if include_optional :
            return Package(
                id = '0', 
                release = '0', 
                slug = 'a', 
                url = '0', 
                size = 56, 
                signature_dsa = '0', 
                signature_eddsa = '0', 
                bundle_version = '0', 
                platform = 'windows', 
                installer_args = '0', 
                installer = 'innosetup'
            )
        else :
            return Package(
                release = '0',
                slug = 'a',
                url = '0',
                bundle_version = '0',
        )

    def testPackage(self):
        """Test Package"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
