# coding: utf-8

"""
    SparkleHub API

    Test description  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: alex@shishenko.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sparklehub.openapi_client
from sparklehub.openapi_client.api.relnotes_api import RelnotesApi  # noqa: E501
from sparklehub.openapi_client.rest import ApiException


class TestRelnotesApi(unittest.TestCase):
    """RelnotesApi unit test stubs"""

    def setUp(self):
        self.api = sparklehub.openapi_client.api.relnotes_api.RelnotesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_relnotes_list(self):
        """Test case for relnotes_list

        """
        pass

    def test_relnotes_read(self):
        """Test case for relnotes_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
