# coding: utf-8

"""
    SparkleHub API

    Test description  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: alex@shishenko.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sparklehub.openapi_client
from sparklehub.openapi_client.api.packages_api import PackagesApi  # noqa: E501
from sparklehub.openapi_client.rest import ApiException


class TestPackagesApi(unittest.TestCase):
    """PackagesApi unit test stubs"""

    def setUp(self):
        self.api = sparklehub.openapi_client.api.packages_api.PackagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_packages_create(self):
        """Test case for packages_create

        """
        pass

    def test_packages_delete(self):
        """Test case for packages_delete

        """
        pass

    def test_packages_list(self):
        """Test case for packages_list

        """
        pass

    def test_packages_partial_update(self):
        """Test case for packages_partial_update

        """
        pass

    def test_packages_read(self):
        """Test case for packages_read

        """
        pass

    def test_packages_update(self):
        """Test case for packages_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
