# coding: utf-8

"""
    SparkleHub API

    Test description  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: alex@shishenko.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sparklehub.openapi_client
from sparklehub.openapi_client.models.release import Release  # noqa: E501
from sparklehub.openapi_client.rest import ApiException

class TestRelease(unittest.TestCase):
    """Release unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Release
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sparklehub.openapi_client.models.release.Release()  # noqa: E501
        if include_optional :
            return Release(
                id = '0', 
                channel = '0', 
                version = '0', 
                published = True, 
                pub_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                title = '0', 
                critical = True
            )
        else :
            return Release(
                channel = '0',
                version = '0',
        )

    def testRelease(self):
        """Test Release"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
