# coding: utf-8

"""
    SparkleHub API

    Test description  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: alex@shishenko.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sparklehub.openapi_client
from sparklehub.openapi_client.api.releases_api import ReleasesApi  # noqa: E501
from sparklehub.openapi_client.rest import ApiException


class TestReleasesApi(unittest.TestCase):
    """ReleasesApi unit test stubs"""

    def setUp(self):
        self.api = sparklehub.openapi_client.api.releases_api.ReleasesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_releases_latest(self):
        """Test case for releases_latest

        """
        pass

    def test_releases_list(self):
        """Test case for releases_list

        """
        pass

    def test_releases_read(self):
        """Test case for releases_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
