# coding: utf-8

"""
    SparkleHub API

    Test description  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: alex@shishenko.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sparklehub.openapi_client
from sparklehub.openapi_client.api.channels_api import ChannelsApi  # noqa: E501
from sparklehub.openapi_client.rest import ApiException


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self):
        self.api = sparklehub.openapi_client.api.channels_api.ChannelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_channels_list(self):
        """Test case for channels_list

        """
        pass

    def test_channels_read(self):
        """Test case for channels_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
